---
name: Visual Studio Bug report
description: Create a report to help us improve the Reqnroll Visual Studio Extension
body:
- type: dropdown 
  attributes:
    label: Used Visual Studio
    options:
      - Visual Studio 2022
  validations:
    required: true
- type: dropdown
  attributes:
    label: Are the latest Visual Studio updates installed?
    options:
      - 'Yes'
      - 'No'
  validations:
    required: true
- type: textarea
  attributes:
    label: Reqnroll Section in app.config or content of reqnroll.json
    placeholder: PLEASE COPY THE ENTIRE <Reqnroll> SECTION IN YOUR .config FILE or THE ENTIRE reqnroll.json
- type: textarea
  attributes:
    label: Issue Description
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to Reproduce
  validations:
    required: true
- type: input
  attributes:
    label: Link to Repository Project
  validations:
    required: false